# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf9dd24dcfa6efd6c3d6f8bc026ad5bbc8f2bf09345a0360660c8515855bdb00518e4c4e5915b2f0505186054d85d3822b741b116b3fc800370eca2a3116a9be

test:
  secret_key_base: 978a45be80e4aed75a989a0ce2149cbf81393e53cffc94a61a8ac4434569069b588fd6bdd7637dc383bf808d609ded506d6a475e45998348db50c7c82ea0bf26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
